name: docker-build-push
description: Build and push a Docker image (single or multi-platform) with automatic disk cleanup

inputs:
  registry:
    required: false
    default: docker.io
    description: Registry host for login
  username:
    required: true
    description: Registry username
  password:
    required: true
    description: Registry password/token
  image:
    required: true
    description: Full image reference with tag (e.g., docker.io/user/app:latest)
  platforms:
    required: false
    default: linux/amd64
    description: Platform(s) to build (comma-separated for multi-platform, e.g., linux/amd64,linux/arm64)
  context:
    required: false
    default: .
    description: Build context path
  dockerfile:
    required: false
    default: Dockerfile
    description: Dockerfile path
  build_args:
    required: false
    default: ""
    description: Build args as newline-separated KEY=VALUE
  cache:
    required: false
    default: true
    description: Enable build cache (true/false)
  push:
    required: false
    default: true
    description: Push image to registry (true/false)
  description_file:
    required: false
    default: README.md
    description: "Path to description file for DockerHub (e.g., README.md, docs/README.md). Skips update if not found."

runs:
  using: composite
  steps:
    -
      name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    -
      name: Setup Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.image }}
        build-args: ${{ inputs.build_args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Update docker description
      uses: hieupth/docker-actions/docker-description@main
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        repository: ${{ inputs.image }}
        description_file: ${{ inputs.description_file }}
