name: docker-multiarch-build
description: Build a single-platform image, push by digest, upload digest as an artifact

inputs:
  registry:
    required: false
    default: docker.io
  username:
    required: true
  password:
    required: true

  image:
    required: true
    description: "Image ref WITHOUT tag. Example: docker.io/user/app"
  tag:
    required: true
    description: "Single tag (caller can pass matrix.tag)"
  platform:
    required: true
    description: "Single platform for this job. Example: linux/amd64"

  context:
    required: false
    default: .
  dockerfile:
    required: false
    default: dockerfile

  build_args:
    required: false
    default: ""

  artifact_prefix:
    required: false
    default: digests
  retention_days:
    required: false
    default: "1"

runs:
  using: composite
  steps:
    - 
      name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - 
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - 
      name: Setup Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - 
      name: Normalize platform tag
      id: plat
      shell: bash
      run: |
        set -euo pipefail
        echo "plat_tag=${{ inputs.platform }}" | sed 's|/|-|g' >> "$GITHUB_OUTPUT"
    - 
      name: Build and push (by digest)
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platform }}
        push: true
        build-args: ${{ inputs.build_args }}
        # Docker-recommended pattern for later manifest merge: push-by-digest + name-canonical  [oai_citation:3‡Docker Documentation](https://docs.docker.com/build/ci/github-actions/multi-platform/?utm_source=chatgpt.com)
        outputs: |
          type=image,name=${{ inputs.image }},push-by-digest=true,name-canonical=true,push=true
    - 
      name: Write digest file
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p /tmp/digests
        echo "${{ steps.build.outputs.digest }}" > "/tmp/digests/${{ inputs.tag }}-${{ steps.plat.outputs.plat_tag }}.digest"
    - 
      name: Upload digest artifact (unique per platform)
      uses: actions/upload-artifact@v4
      with:
        # artifact names must be unique in v4 (immutable/idempotent)  [oai_citation:4‡GitHub](https://github.com/actions/upload-artifact?utm_source=chatgpt.com)
        name: ${{ inputs.artifact_prefix }}-${{ inputs.tag }}-${{ steps.plat.outputs.plat_tag }}
        path: /tmp/digests/*.digest
        if-no-files-found: error
        retention-days: ${{ inputs.retention_days }}