name: docker-multiarch-merge
description: Download digest artifacts and create a multi-arch manifest tag

inputs:
  registry:
    required: false
    default: docker.io
  username:
    required: true
  password:
    required: true
  image:
    required: true
    description: "Image ref WITHOUT tag. Example: docker.io/user/app"
  tag:
    required: true
    description: "Single tag to publish"
  artifact_prefix:
    required: false
    default: digests
  digests_path:
    required: false
    default: /tmp/digests
  description_file:
    required: false
    default: README.md
    description: "Path to description file for DockerHub (e.g., README.md, docs/README.md). Skips update if not found."

runs:
  using: composite
  steps:
    - 
      name: Setup Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - 
      name: Download digest artifacts
      uses: actions/download-artifact@v4
      with:
        # v4 supports pattern + merge-multiple to download many artifacts into one directory  [oai_citation:5‡The GitHub Blog](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/?utm_source=chatgpt.com)
        pattern: ${{ inputs.artifact_prefix }}-${{ inputs.tag }}-*
        path: ${{ inputs.digests_path }}
        merge-multiple: true
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set GitHub Path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    -
      name: Create and push manifest list
      run: create-manifest.sh
      shell: bash
      env:
        INPUT_IMAGE: ${{ inputs.image }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_DIGESTS_PATH: ${{ inputs.digests_path }}
    -
      name: Update docker description
      uses: hieupth/docker-actions/docker-description@main
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        repository: ${{ inputs.image }}
        description_file: ${{ inputs.description_file }}